on:
  push:
    branches: [blueprint]
  pull_request:
  workflow_dispatch:
name: Build Flatpak
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.2
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    # Docker is required by the docker/setup-qemu-action which enables emulation
    - name: Install Docker dependency
      run: |
        dnf -y install docker
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: "thebeat.flatpak"
        manifest-path: "dist/com.vicr123.thebeat_blueprint.yml"
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}
    - uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v4
      name: "Deploy"
      with:
        repository: blueprint
        flat-manager-url: https://flatpak.vicr123.com
        token: ${{ secrets.REPO_TOKEN }}
