name: CI

on:
  push:
    branches: 
      - master
      - blueprint

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: vicr123/the-libs/bootstrap@actions
      name: "Bootstrap Build"
      with:
        extra-deps-linux: "libtag1-dev"
        extra-deps-mac: "taglib libmusicbrainz"
    - uses: vicr123/contemporary-theme/actions/build@master
      name: Build Contemporary
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - uses: vicr123/the-libs/build@actions
      name: "Build Project"
    - name: "Prepackage Project (macOS)"
      run: ./ci/extra-steps-mac.sh
      if: runner.os == 'macOS'
    - uses: vicr123/the-libs/image@actions
      name: "Package Project"
      id: image
      with:
        extra-plugins-linux: "styles/libContemporary.so"
        image-name-linux: theBeat-linux.AppImage
        app-bundle-mac: "application/theBeat.app"
        embed-libraries-mac: "tag"
        embed-local-libraries-mac: "libthebeat/libthebeat.dylib"
    - uses: actions/upload-artifact@v1
      name: Upload Artifact to GitHub Actions
      with:
        name: ${{ steps.image.outputs.asset-name }}
        path: ${{ steps.image.outputs.image-path }}
    - uses: vicr123/create-release@delete-old-release
      name: "Create Release"
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: continuous
        release_name: Continuous Build
        replace_old_tag: true
        prerelease: true
    - uses: actions/upload-release-asset@v1.0.1
      name: "Upload Release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.image.outputs.image-path }}
        asset_name: ${{ steps.image.outputs.asset-name }}
        asset_content_type: ${{ steps.image.outputs.asset-content-type }}
